### ISSUE TITLE
16计科1班 谢欣蓓

### ISSUE THREAD

**Issue by Bella-X** [huashangxueyuan/hackathon_round_1#4]

**Comment by Bella-X** [comment]
[](url)

**Comment by Bella-X** [comment]
[quickstart.zip](https://github.com/huashangxueyuan/hackathon_round_1/files/2534447/quickstart.zip)

**Comment by Candiceljy** [comment]
oh~需要提交仓库地址哦，你这个是压缩包。赶紧把地址甩上来，马上就可以完成站点一了。
