### ISSUE TITLE
15计科1-朱彬彬

### ISSUE THREAD

**Issue by enjoy-binbin** [huashangxueyuan/hackathon_round_1#7]
仓库地址：
https://github.com/enjoy-binbin/QuickStart

心得：现在小程序也越来越，先进了，记得第一次写小程序的时候，是17年的寒假一月份多的样子吧，那时候小程序刚出，希望通过这次马拉松，可以回顾回顾小程序hhhh

**Comment by Candiceljy** [comment]
good good！ 非常棒，有基础还耐心学习，有程序员的味道。加油！
