### ISSUE TITLE
17计科三班-黄燕惟

### ISSUE THREAD

**Issue by Huangyanwei** [huashangxueyuan/hackathon_round_1#82]
一定要好好学习每一个课程！！因为短时间内学习的内容比较多，容易混淆或者遗忘，所以要慢慢消化学习内容，最好是有空的时候多看几遍视频，有利于加深记忆，绝对不可以生搬硬套！要去理解每一个过程，否则是不会有好的学习效果的。
这次的实验就是花费太多时间了，因为在github page的学习中，由于有较多的课程内容，所以导致没有办法好好记下来，有花费了很多时间去重新回顾，不过重新回顾一遍也是好的，这次的经验教训让我在以后的课程学习中会更合理地安排系统化的学习~~
这是本次作业的代码地址：
https://github.com/Huangyanwei/Quickstart

**Comment by Candiceljy** [comment]
学习态度非常棒，恭喜你通过任务一考核。
