### ISSUE TITLE
17计科三班杨静娴

### ISSUE THREAD

**Issue by yangjingxian** [huashangxueyuan/hackathon_round_1#95]
本次任务的地址：https://github.com/yangjingxian/quickstart
不知道有没有错误的地方，请老师检阅。这次任务一直拖到最后一天交真的很愧疚，因为一直在弄，但是最后一步同步到远程仓库总是不成功，重新尝试了很多遍还是不行，最后才发现应该是SSH KEY设置可能出了错误，然后删除了原本的SSH，重新设置了一遍，就同步成功了！希望接下来可以学习到更多东西！

**Comment by Candiceljy** [comment]
恭喜你通过任务一考核，非常棒！继续加油！
